### ISSUE TITLE
Sur device Android, les icones du burger menu sont mal affichées

### ISSUE THREAD

**Issue by lherarnaud** [XavierBorelly/Familink#32]
Quand on utilise un device Android, les icônes du burger menu sont tronqués.
Le package.json utilisé est un fork de React Navigation ("https://github.com/martnu/react-navigation#pass-down-drawer-lock-mode") où la taille des icônes du DrawerNavigator est limité à 24x24 pixels. A noter qu'il existe une propriété contentComponent pour customiser le burger menu.
Il faut donc faire le nécéssaire pour avoir de belles icônes de forme carré.

**Comment by gbattez** [comment]
fixed
