### ISSUE TITLE
Fonction Utils MD5

### ISSUE THREAD

**Issue by lherarnaud** [XavierBorelly/Familink#33]
La fonction MD5 de la classe Utils a généré environ 60 retours négatifs de la part de SonarQube.
Il faut corriger ce défaut en trouvant une alternative. 
A noter que :
- le composant Gravatar a besoin d'une fonction md5(string)
- la source de ce code devrait être cité
- Sonar vérifie les règles JS et ESLint.

**Comment by gbattez** [comment]
fixed
