### ISSUE TITLE
Warning BackAndroid

### ISSUE THREAD

**Issue by lherarnaud** [XavierBorelly/Familink#38]
Si on désactive la ligne 

`console.ignoredYellowBox = ['Warning:'];`

du fichier index.ios.js, j'ai le message de warning suivant quand j'utilise mon device Android : 

> "BackAndroid is deprecated. Please use BackHandler instead."

Il faut faire disparaître ce message

**Comment by gbattez** [comment]
C'est un bug qui vient d'un node_module, c'est donc pas a nous de s'en charger
